### PR TITLE
tests/binder: Build only for 4.11 and later kernels

### PR DESCRIPTION
**Pull request by Raverstern**
Following compilation errors occur when building the tests with userspace headers exported from kernel 4.4:

```
binder_common.c:111:14: error: ‘const struct flat_binder_object’ has no
member named ‘hdr’
   switch (obj->hdr.type) {
              ^
client.c:58:9: error: dereferencing pointer to incomplete type
  if (obj->hdr.type != BINDER_TYPE_FD) {
         ^
```

It's been checked that member `hdr` of `struct flat_binder_object` and `struct binder_fd_object` were both introduced by commit feba3900cabb ("binder: Split flat_binder_object") in kernel v4.11-rc1. Fix this by adding kernel version check at compile time.

### CODE REVIEW

**Comment by pcmoore** [comment]
On-list patch via patchwork:
* https://patchwork.kernel.org/project/selinux/patch/20220113020915.13560-1-gongruiqi1@huawei.com
